### ISSUE TITLE
App error

### ISSUE THREAD

**Issue by kirillrybin** [namuol/spotify-desktop-remote#1]
When I try open this link 

```
spotify:app:spotify-desktop-remote
```

I get an error:
![Error](http://i.imgur.com/5V7mxLV.png)

**Comment by namuol** [comment]
- What platform(s) are you using?
- Ensure you have a [premium spotify account, registered as a developer](https://devaccount.spotify.com/my-account/).
- Ensure you have the [app installed](https://github.com/namuol/spotify-desktop-remote#installation).

**Comment by namuol** [comment]
Closing for now -- desktop apps are known to have been "discontinued" for some time now, so that is the likely culprit.
