### ISSUE TITLE
No longer working 

### ISSUE THREAD

**Issue by EwanRoberts** [namuol/spotify-desktop-remote#2]
Save yourself some time, this only worked with the old Spotify. Spotify doesn't allow addons anymore

**Comment by namuol** [comment]
I can still get it to run in Linux, but I'm guessing their Linux client doesn't get updated as often.

It might also just be that existing apps get "grandfathered" in. Hard for me to test without a fresh install.

I'll make a note on the README that this probably wont work anymore.
