### ISSUE TITLE
Spotify's New Support For Apps?

### ISSUE THREAD

**Issue by Zxlfie** [namuol/spotify-desktop-remote#3]
Hey! I know this is quite old but when trying to install your desktop remote, I noticed a folder which contains .spa files called "Apps". I was just wondering if you could do anything with that.

**Comment by namuol** [comment]
Is there something explicitly outlined in Spotify's documentation about these sorts of Apps?

**Comment by Zxlfie** [comment]
Sadly, no. But I did some research on the files within the app folder (which were .spa files) and found out they are a bit like .zip files, where within, there is a similar structure to the app you had made.

**Comment by namuol** [comment]
I encourage you to attempt to retrofit `spotify-desktop-remote` into this format -- let me know if it works for you! :)

**Comment by Zxlfie** [comment]
Well, I did try to do so, but the only problem is that you used npm to make everything run.

**Comment by namuol** [comment]
Why would NPM pose an issue? The only thing that needs to exist in the app is the static HTML page that connects to the server that runs via NPM, right?

**Comment by Zxlfie** [comment]
Oh yes, that's true. It must be another issue then.

**Comment by namuol** [comment]
Side note: Thank you for trying to raise this project from the dead without any help from me; I wish had more time to assist. :heart:

**Comment by Zxlfie** [comment]
It's fine :)! I really love this project and find it very interesting. Seeing something like this be revived would be really nice.

**Comment by Zxlfie** [comment]
Also, a quick note, so far, I was able to get this working within Spotify:
![image](https://cloud.githubusercontent.com/assets/21978188/19170576/f2486788-8c10-11e6-82a4-a1790d6eac71.png)

**Comment by namuol** [comment]
If you can open developer tools and look at the console you should be able to figure out why it's failing to connect to the local server. :) I'm guessing this is still a very fragile thing to support since it's not officially documented by Spotify, but it's good to know nonetheless.

**Comment by DevinNorgarb** [comment]
@namuol @Zxlfie Sorry to completely raising this up from 4 years ago but Spotify still doesn't have have any WS endpoints for us to subscribe to. 
Libraries like this which a provide a socket interface to Spotify's API are awesome! 
Thanks for this library.  

Will likely implement some of this libraries functionality into one of my side project which will be  perfect for what I need to achieve. 
Feel free to check out my app below.  Would love some opinions :)

https://play.google.com/store/apps/details?id=org.devinnorgarb.spotifyvoice

**Comment by namuol** [comment]
@DevinNorgarb Thanks for the nice words! How are you planning to implement things? I'm assuming that my library does _not_ work anymore - I haven't tried in years!

(I'm closing this issue since it doesn't seem like  but we can continue the discussion 👍)
