### ISSUE TITLE
Another possibile alternative

### ISSUE THREAD

**Issue by benjaminwood** [namuol/spotify-desktop-remote#4]
From the readme

> If you can think of an alternative way to control Spotify Desktop with a similar interface, please let me know!

After coming across spotify-desktop-remote, I continued on to discover this: https://github.com/onetune/spotify-web-helper

I haven't tried it yet, but it looks promising and perhaps it should be listed as an alternative as well.

**Comment by namuol** [comment]
Thanks @benjaminwood! I'll add this to the README 👏

**Comment by namuol** [comment]
Fixed in 7d820008cdcadf206f3ba1ccc5d993cdd6609da6.

**Comment by benjaminwood** [comment]
Cool, thanks!

**Comment by Elompenta** [comment]
not working anymore :(
https://github.com/onetune/spotify-web-helper/issues/41
